stages:
  - stamp

stamp:
  image: docker:git
  services:
  - docker:dind
  stage: stamp
  before_script:
    - apk add --update nodejs nodejs-npm
    - npm install -g semantic-release@15 @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/npm
  script:
    - npx semantic-release -r https://github.com/Cosmic9Studios/pulumi-nomad.git
  except: 
    - tags
  only: 
    - master